apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-znyo
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-rhqr-tenant/rhtap-demo-app/hacbs-test-project-znyo@sha256:e1dce3f655cb5f1091fd446685d1df0f15aa567c3c2bd6855e09ccb9d61ec51d
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
