apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-znyo
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-rhqr-tenant/rhtap-demo-app/hacbs-test-project-znyo@sha256:893c4563244970eb44a7426f7d591b7888fb8d2350e4d24d94bd72c3695c6884
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
