apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-znyo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-znyo
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-znyo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-znyo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-znyo
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-rhqr-tenant/rhtap-demo-app/hacbs-test-project-znyo@sha256:893c4563244970eb44a7426f7d591b7888fb8d2350e4d24d94bd72c3695c6884
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
